version: '3.8'
services:
  movies_database:
    container_name: movies_database
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata

    ports:
      - "5432:5432"
    volumes:
      - movies_database_vol:/var/lib/postgresql/data
      - /Users/alibashir/Desktop/workspace.nosync/ETL/netflix_dataflow_mimic/docker/movies_database/data/cleaned_data:/resources/data/movies_data
      - /Users/alibashir/Desktop/workspace.nosync/ETL/netflix_dataflow_mimic/docker/movies_database/data/test_data:/resources/data/movies_test_data
      - /Users/alibashir/Desktop/workspace.nosync/ETL/netflix_dataflow_mimic/docker/movies_database/scripts:/docker-entrypoint-initdb.d
  movies_database_api:
    container_name: movies_database_api
    build: docker/movies_database_api
    environment:
      PYTHONPATH: /netflix_mimic_app
    volumes:
      - /Users/alibashir/Desktop/workspace.nosync/ETL/netflix_dataflow_mimic/movies_database_api:/netflix_mimic_app/movies_database_api
      - netflix_mimic_shared_vol:/secret
    ports:
      - "8000:8000"
  netflix_mimic_app:
    container_name: netflix_mimic_app
    build: docker/netflix_mimic_app
    environment:
      PYTHONPATH: /netflix_mimic_app
    volumes:
      - /Users/alibashir/Desktop/workspace.nosync/ETL/netflix_dataflow_mimic/netflix_mimic_app:/netflix_mimic_app
      - netflix_mimic_shared_vol:/secret
volumes:
  movies_database_vol:
    driver: local
  netflix_mimic_shared_vol:
    driver: local